server.port=8081

#DB properties
db.port=5432
db.name=filesBase-security
db.ipServer=localhost
db.server=postgresql
db.userName=postgres
db.userPassword=admin
db.sqlDialect=PostgreSQLDialect

#ORM - Hibernate properties
orm.session.package=com.ms.login

# DataSource configuration
#spring.datasource.url=jdbc:postgresql://localhost:5432/filesBase-security
#spring.datasource.username=postgres
#spring.datasource.password=admin
#spring.datasource.driverClassName=org.postgresql.Driver 

# Hibernate configuration
#spring.jpa.hibernate.ddl-auto=validate
#spring.jpa.show-sql=true


#log4j.logger.org.hibernate=DEBUG
#log4j.logger.org.hibernate.SQL=DEBUG
#log4j.logger.org.hibernate.type.descriptor.sql=TRACE